Recording branch
midichrolians/midichrolian-ios pull request #117
Opened 2017-04-07 18:38 UTC by Tzyinc

2017-04-07 18:41 UTC, Tzyinc commented on MIDIchlorians/MIDIchlorians/RecorderManager.swift
> +                print("page", value.1.0, "index", value.1.1)
need @ngzhian 's help to play pad from page

2017-04-08 05:52 UTC, ngzhian commented on MIDIchlorians/MIDIchlorians/RecorderManager.swift
> +                print("page", value.1.0, "index", value.1.1)
can make a `RecordPlaybackDelegate` protocol with a play method, then I'll make `GridController` implement it

2017-04-08 08:34 UTC, ngzhian requested changes

2017-04-08 08:34 UTC, ngzhian commented on MIDIchlorians/MIDIchlorians/RecorderManager.swift
> +    private let TIMEINTERVAL: TimeInterval = 1/60
Throw this into Config?

2017-04-08 08:34 UTC, ngzhian commented on MIDIchlorians/MIDIchlorians/TimeTracker.swift
> +    private let PLAYBACKACCURACY: TimeInterval = 1/60
throw into Config

2017-04-08 08:34 UTC, ngzhian commented on MIDIchlorians/MIDIchlorians/PlayBackRetriever.swift
> +    mutating func getNextPads() -> [(TimeInterval, (Int, IndexPath))] {
what is this method trying to do actually, is it returning all pads that have the same time interval?

2017-04-08 08:34 UTC, ngzhian commented on MIDIchlorians/MIDIchlorians/RecorderManager.swift
> +    func recordPad (forPage pageNum: Int, forIndex indexPath: IndexPath) {
nit: no space between method name and parentheses

2017-04-08 14:48 UTC, Tzyinc commented on MIDIchlorians/MIDIchlorians/RecorderManager.swift
> +    func recordPad (forPage pageNum: Int, forIndex indexPath: IndexPath) {
good catch

2017-04-08 14:49 UTC, Tzyinc commented on MIDIchlorians/MIDIchlorians/PlayBackRetriever.swift
> +    mutating func getNextPads() -> [(TimeInterval, (Int, IndexPath))] {
yes, it's returning all pads with the same time interval, to be called when the current pads have been played (think of it like buffering the next pads to play)

2017-04-08 17:27 UTC, ngzhian approved these changes

2017-04-08 17:27 UTC, ngzhian commented
Fix conflicts and can merge :) Nice!

2017-04-08 17:29 UTC, merged