Added capability to convert animation sequence to json string
midichrolians/midichrolian-ios pull request #5
Opened 2017-03-17 11:19 UTC by anand-sundaram

(Also abstracted the `UIColor`s  currently used into an enum called Colour)

`AnimationSequence` can be serialized into a JSON string so @advaypal can store it easily using realm.

- `getJSON() -> String`
- `AnimationSequence.getAnimationSequenceFromJSON(fromJSON: String) -> AnimationSequence`

2017-03-19 02:59 UTC, ngzhian requested changes

2017-03-19 02:59 UTC, ngzhian commented on MIDIchlorians/MIDIchlorians/AnimationBit.swift
> +    static private let colourKey = "colour"
extract to config file?

2017-03-19 02:59 UTC, ngzhian commented on MIDIchlorians/MIDIchlorians/AnimationBit.swift
> +    static private let colourKey = "colour"
same for `rowKey` and `columnKey`

2017-03-19 02:59 UTC, ngzhian commented on MIDIchlorians/MIDIchlorians/AnimationSequence.swift
> +        var arrayOfStrings = [[String]?]()
maybe call this something like, animationSequence? Cos it's an animation sequence JSON in string form right?

2017-03-20 09:02 UTC, anand-sundaram commented
@ngzhian made some changes based on your review.

2017-03-20 12:36 UTC, ngzhian approved these changes

2017-03-20 12:36 UTC, merged

2017-03-20 12:36 UTC, ngzhian commented
LGTM, so merged this in. @advaypal please merge this into your local branch and make changes based on this