Add the models
midichrolians/midichrolian-ios pull request #7
Opened 2017-03-17 12:30 UTC by advaypal

Still WIP. DO NOT MERGE

2017-03-18 12:13 UTC, advaypal commented
Guys, this is most of the code for the models and the data storage, tell me what you guys think and whether I should make changes?
@anand-sundaram @Tzyinc Let me know when you have the serialisation function and audio struct ready respectively, will update accordingly

2017-03-18 14:27 UTC, anand-sundaram commented
@advaypal I have added the serialization function in #5 
You can try rebasing this branch on top of that if it looks okay to you.

2017-03-19 02:53 UTC, ngzhian requested changes
Looks great, check out inline comments related to constants and `prepareForSave`.

2017-03-19 02:53 UTC, ngzhian commented on MIDIchlorians/MIDIchlorians/Pad.swift
> +        //add audio here
what's this comment about?

2017-03-19 02:53 UTC, ngzhian commented on MIDIchlorians/MIDIchlorians/Pad.swift
> +
does this need to be implemented?

2017-03-19 02:53 UTC, ngzhian commented on MIDIchlorians/MIDIchlorians/Session.swift
> +    dynamic private var BPM = 0 // Need to agree on a default value
let's put it at 128 for now, we might not even get to implement this

2017-03-19 02:53 UTC, ngzhian commented on MIDIchlorians/MIDIchlorians/Session.swift
> +    dynamic private var numPages = 0
use constants from config? same as fields below `numRows`, `numCols`

2017-03-19 02:53 UTC, ngzhian commented on MIDIchlorians/MIDIchlorians/Session.swift
> +    dynamic private var BPM = 0 // Need to agree on a default value
also, put this constant in config

2017-03-19 02:53 UTC, ngzhian commented on MIDIchlorians/MIDIchlorians/Session.swift
> +                    padList.append(pad)
think we need to reset `padList` everytime we call this `prepareForSave`, otherwise we keep appending pads.

2017-03-19 02:53 UTC, ngzhian commented on MIDIchlorians/MIDIchlorians/Session.swift
> +            pads.append([])
reset pads to `[]`?

2017-03-19 02:53 UTC, ngzhian commented on MIDIchlorians/MIDIchlorians/SessionSaver.swift
> +        let session = realm.objects(Session.self).filter("sessionName = %@", sessionName)[0]
extract this string into constant
and use `.first`

2017-03-21 11:04 UTC, advaypal commented on MIDIchlorians/MIDIchlorians/Pad.swift
> +
Yup, will call the serialisation functions here

2017-03-21 11:04 UTC, advaypal commented on MIDIchlorians/MIDIchlorians/Session.swift
> +    dynamic private var BPM = 0 // Need to agree on a default value
Got it

2017-03-21 11:04 UTC, advaypal commented on MIDIchlorians/MIDIchlorians/Session.swift
> +                    padList.append(pad)
(y)

2017-03-21 11:05 UTC, advaypal commented on MIDIchlorians/MIDIchlorians/Session.swift
> +            pads.append([])
Ok

2017-03-21 11:05 UTC, advaypal commented on MIDIchlorians/MIDIchlorians/SessionSaver.swift
> +        let session = realm.objects(Session.self).filter("sessionName = %@", sessionName)[0]
Ok

2017-03-21 11:05 UTC, advaypal commented on MIDIchlorians/MIDIchlorians/Pad.swift
> +        //add audio here
Need to add the name of the audio property here, to tell Realm that it's not needed

2017-03-21 11:29 UTC, advaypal commented on MIDIchlorians/MIDIchlorians/Pad.swift
> +        //add audio here
Doesn't matter if we're only storing audio files

2017-03-21 12:19 UTC, advaypal commented
@ngzhian Take a look at the changes. Have added the saving/loading methods which currently do not work, but can be merged in so that everyone can work with them

2017-03-21 12:25 UTC, advaypal commented
Don't merge it in yet though, I'll merge it once you've reviewed. Had temporarily removed SwiftLint and am adding it back now

2017-03-21 13:15 UTC, merged